#!/usr/bin/env bash
# ---------------------------------------------------------------------------
# Refresh the Cloudflare-only origin allow-list.
#
#   sudo bash deploy/refresh-cloudflare-ips.sh
#
# Cloudflare publishes its edge ranges and changes them occasionally, so this
# file is GENERATED rather than committed. A stale list is not a subtle
# failure — it is either a site that 403s its own CDN, or an origin lock with
# a hole in it. Re-run this after any Cloudflare announcement about ranges.
#
#   https://www.cloudflare.com/ips/
#
# Two files come out of the same list, because nginx needs the ranges in two
# different syntaxes:
#
#   cloudflare-only.conf   `allow 1.2.3.0/24;`   → the origin lock
#   cloudflare-geo.conf    `1.2.3.0/24 1;`       → a `geo` lookup, so the
#                                                  logging map can tell a real
#                                                  Cloudflare edge from a
#                                                  direct connection
#
# Both are included with a trailing `*`. nginx treats a missing literal include
# as fatal but a wildcard with no matches as nothing to do, so:
#
#   • a fresh box that has not run this script still starts nginx, and
#   • ROLLBACK IS `rm` — delete the files, reload, and the origin is public
#     again, with no config edit and no chance of a half-edited file.
# ---------------------------------------------------------------------------
set -euo pipefail

ALLOW="/etc/nginx/snippets/cloudflare-only.conf"
GEO="/etc/nginx/snippets/cloudflare-geo.conf"
RAW="$(mktemp)"
ALLOW_TMP="$(mktemp)"
GEO_TMP="$(mktemp)"
trap 'rm -f "$RAW" "$ALLOW_TMP" "$GEO_TMP"' EXIT

echo "==> fetching Cloudflare's published ranges"
for family in ips-v4 ips-v6; do
    url="https://www.cloudflare.com/${family}"
    if ! list="$(curl -fsS --max-time 20 "$url")"; then
        echo "failed to fetch $url — nothing installed" >&2
        exit 1
    fi
    # Printed, not appended with `>>`: Cloudflare's v4 list does not end in a
    # newline, so appending the v6 list straight onto it fused the last IPv4
    # range and the first IPv6 range into "131.0.72.0/222400:cb00::/32" and
    # nginx refused the whole file. printf guarantees the separator.
    printf '%s\n' "$list" >> "$RAW"
done

# Normalise: drop blanks and comments, keep one CIDR per line.
sed -i '/^[[:space:]]*$/d; /^[[:space:]]*#/d; s/[[:space:]]*$//' "$RAW"

COUNT="$(wc -l < "$RAW" | tr -d ' ')"

# Refuse to install a list that is obviously incomplete. `deny all;` with no
# allows would take the entire site down, and the symptom — every visitor
# getting a 403 — reads exactly like a Cloudflare outage, which is the wrong
# place to start looking. Cloudflare publishes ~15 IPv4 and ~7 IPv6 ranges.
if [ "$COUNT" -lt 10 ]; then
    echo "REFUSING to install: only ${COUNT} ranges fetched (expected 20+)." >&2
    echo "Existing files left untouched." >&2
    exit 1
fi

{
    echo "# GENERATED by deploy/refresh-cloudflare-ips.sh — do not edit by hand."
    echo "#"
    echo "# Cloudflare's edge ranges as an allow-list. A request that is not from"
    echo "# one of these is refused, so the origin cannot be reached by its own IP"
    echo "# and Cloudflare's WAF cannot be bypassed. Delete this file to make the"
    echo "# origin public again."
    echo "#"
    echo "#   https://www.cloudflare.com/ips/"
    echo
    sed 's/^/allow /; s/$/;/' "$RAW"
    echo
    echo "deny all;"
} > "$ALLOW_TMP"

{
    echo "# GENERATED by deploy/refresh-cloudflare-ips.sh — do not edit by hand."
    echo "#"
    echo "# The same ranges in \`geo\` syntax. This is what lets the logging map"
    echo "# distinguish a genuine Cloudflare edge from anything else, so that"
    echo "# CF-Connecting-IP is only believed when Cloudflare actually set it."
    echo "#"
    echo "#   https://www.cloudflare.com/ips/"
    echo
    sed 's/$/ 1;/' "$RAW"
} > "$GEO_TMP"

install -m 644 "$ALLOW_TMP" "$ALLOW"
install -m 644 "$GEO_TMP" "$GEO"

echo "wrote $ALLOW and $GEO (${COUNT} ranges)"
if command -v nginx >/dev/null 2>&1; then
    nginx -t && echo "run:  systemctl reload nginx"
fi
