#!/usr/bin/env bash
# ---------------------------------------------------------------------------
# Refresh the Cloudflare-only origin allow-list.
#
#   sudo bash deploy/refresh-cloudflare-ips.sh
#
# Cloudflare publishes its edge ranges and changes them occasionally, so this
# file is GENERATED rather than committed. A stale list is not a subtle
# failure — it is either a site that 403s its own CDN, or an origin lock with
# a hole in it. Re-run this after any Cloudflare announcement about ranges.
#
#   https://www.cloudflare.com/ips/
#
# The output is installed as /etc/nginx/snippets/cloudflare-only.conf, which
# the site config includes with a trailing `*`:
#
#   include /etc/nginx/snippets/cloudflare-only.conf*;
#
# That wildcard is deliberate. nginx treats a missing literal include as a
# fatal error but a wildcard with no matches as nothing to do, so:
#
#   • a fresh box that has not run this script still starts nginx, and
#   • ROLLBACK IS `rm` — delete the file, reload, and the origin is public
#     again, with no config edit and no chance of a half-edited file.
# ---------------------------------------------------------------------------
set -euo pipefail

OUT="/etc/nginx/snippets/cloudflare-only.conf"
TMP="$(mktemp)"
trap 'rm -f "$TMP"' EXIT

{
    echo "# GENERATED by deploy/refresh-cloudflare-ips.sh — do not edit by hand."
    echo "#"
    echo "# Cloudflare's published edge ranges, as an allow-list. A request that"
    echo "# is not from one of these is refused, so the origin cannot be reached"
    echo "# by its own IP address and Cloudflare's WAF cannot be bypassed."
    echo "#"
    echo "# Empty this file (or delete it) to make the origin public again."
    echo "#   https://www.cloudflare.com/ips/"
    echo

    for family in iv4 iv6; do
        url="https://www.cloudflare.com/${family}"
        if ! list="$(curl -fsS --max-time 20 "$url")"; then
            echo "failed to fetch $url" >&2
            exit 1
        fi
        printf '%s\n' "$list" | sed '/^[[:space:]]*$/d'
    done
} > "$TMP.raw"

# Every range becomes its own `allow`, then a single catch-all `deny` last.
# Order matters: nginx checks these top to bottom and stops at the first
# match, so the deny has to come after every allow.
{
    grep -v '^#' "$TMP.raw" | grep -v '^[[:space:]]*$' | sed 's/^/allow /; s/$/;/'
    echo
    echo "deny all;"
} > "$TMP"

COUNT="$(grep -c '^allow ' "$TMP" || true)"

# Refuse to install an allow-list with nothing in it. `deny all;` on its own
# would take the entire site down, and the symptom — every visitor getting a
# 403 — reads exactly like a Cloudflare outage, which is the wrong place to
# start looking. Cloudflare publishes around 15 IPv4 and 7 IPv6 ranges; well
# under 10 means the fetch went wrong.
if [ "$COUNT" -lt 10 ]; then
    echo "REFUSING to install: only ${COUNT} ranges fetched (expected 20+)." >&2
    echo "Existing $OUT left untouched." >&2
    exit 1
fi

install -m 644 "$TMP" "$OUT"

echo "wrote $OUT (${COUNT} allow-ranges + deny all)"
if command -v nginx >/dev/null 2>&1; then
    nginx -t
    echo "run:  systemctl reload nginx"
fi
