#!/usr/bin/env bash
# ---------------------------------------------------------------------------
# Refresh the Cloudflare-only origin allow-list.
#
#   sudo bash deploy/refresh-cloudflare-ips.sh
#
# Cloudflare publishes its edge ranges and changes them occasionally, so this
# file is GENERATED rather than committed. A stale list is not a subtle
# failure — it is either a site that 403s its own CDN, or an origin lock with
# a hole in it. Re-run this after any Cloudflare announcement about ranges.
#
#   https://www.cloudflare.com/ips/
#
# Two files come out of the same list, because nginx needs the ranges in two
# different syntaxes:
#
#   cloudflare-only.conf   `allow 1.2.3.0/24;`   → the origin lock
#   cloudflare-geo.conf    `1.2.3.0/24 1;`       → a `geo` lookup, so the
#                                                  logging map can tell a real
#                                                  Cloudflare edge from a
#                                                  direct connection
#
# Both are included with a trailing `*`. nginx treats a missing literal include
# as fatal but a wildcard with no matches as nothing to do, so:
#
#   • a fresh box that has not run this script still starts nginx, and
#   • ROLLBACK IS `rm` — delete the files, reload, and the origin is public
#     again, with no config edit and no chance of a half-edited file.
# ---------------------------------------------------------------------------
set -euo pipefail

ALLOW="/etc/nginx/snippets/cloudflare-only.conf"
GEO="/etc/nginx/snippets/cloudflare-geo.conf"
RAW="$(mktemp)"
ALLOW_TMP="$(mktemp)"
GEO_TMP="$(mktemp)"
trap 'rm -f "$RAW" "$ALLOW_TMP" "$GEO_TMP"' EXIT

# Always leave a loadable geo file behind. The site config includes it with a
# wildcard, and nginx tolerates a missing file there — but `$tk_edge` would
# then be undefined and the logging `map` that references it is a hard config
# error. So a fetch failure degrades the logging (every request is treated as
# non-Cloudflare, which falls back to the TCP peer — correct, just less
# informative) rather than leaving a file that cannot start nginx.
write_geo_default() {
    {
        echo "# GENERATED by deploy/refresh-cloudflare-ips.sh"
        echo "#"
        echo "# The range fetch has never succeeded, so no peer is treated as"
        echo "# Cloudflare and the log falls back to the TCP peer address."
        echo "geo \$remote_addr \$tk_edge {"
        echo "    default 0;"
        echo "}"
    } > "$GEO_TMP"
    install -m 644 "$GEO_TMP" "$GEO"
}

echo "==> fetching Cloudflare's published ranges"
FETCH_OK=1
for family in ips-v4 ips-v6; do
    url="https://www.cloudflare.com/${family}"
    if ! list="$(curl -fsS --max-time 20 "$url")"; then
        echo "failed to fetch $url" >&2
        FETCH_OK=0
        break
    fi
    # Printed, not appended with `>>`: Cloudflare's v4 list does not end in a
    # newline, so appending the v6 list straight onto it fused the last IPv4
    # range and the first IPv6 range into "131.0.72.0/222400:cb00::/32" and
    # nginx refused the whole file. printf guarantees the separator.
    printf '%s\n' "$list" >> "$RAW"
done

if [ "$FETCH_OK" -eq 0 ]; then
    # The allow-list is the dangerous one: writing it from a failed fetch
    # would be `deny all;` with no allows, which takes the whole site down and
    # looks like a Cloudflare outage. It is left exactly as it was.
    write_geo_default
    echo "fetch failed — allow-list left untouched, geo file left loadable" >&2
    exit 1
fi

# Normalise: drop blanks and comments, keep one CIDR per line.
sed -i '/^[[:space:]]*$/d; /^[[:space:]]*#/d; s/[[:space:]]*$//' "$RAW"

COUNT="$(wc -l < "$RAW" | tr -d ' ')"

# Refuse to install a list that is obviously incomplete. Cloudflare publishes
# ~15 IPv4 and ~7 IPv6 ranges; well under that means the fetch went wrong.
if [ "$COUNT" -lt 10 ]; then
    write_geo_default
    echo "REFUSING to install: only ${COUNT} ranges fetched (expected 20+)." >&2
    echo "Allow-list left untouched." >&2
    exit 1
fi

{
    echo "# GENERATED by deploy/refresh-cloudflare-ips.sh — do not edit by hand."
    echo "#"
    echo "# Cloudflare's edge ranges as an allow-list. A request that is not from"
    echo "# one of these is refused, so the origin cannot be reached by its own IP"
    echo "# and Cloudflare's WAF cannot be bypassed."
    echo "#"
    echo "# DELETE THIS FILE to make the origin public again. The matching geo"
    echo "# file is separate on purpose — see the note in it."
    echo "#"
    echo "#   https://www.cloudflare.com/ips/"
    echo
    sed 's/^/allow /; s/$/;/' "$RAW"
    echo
    echo "deny all;"
} > "$ALLOW_TMP"

{
    echo "# GENERATED by deploy/refresh-cloudflare-ips.sh — do not edit by hand."
    echo "#"
    echo "# Lets the logging map tell a genuine Cloudflare edge from anything"
    echo "# else, so CF-Connecting-IP is only believed when Cloudflare really set"
    echo "# it. Without that test a direct request could put any address it liked"
    echo "# in the first log field, and the log is what an operator reads to"
    echo "# decide who to block."
    echo "#"
    echo "# The WHOLE geo block is generated, not just its contents, and included"
    echo "# from the site config with a wildcard. nginx does not expand a"
    echo "# wildcard for an include nested inside a geo block — it fails with"
    echo "# 'open() ...: No such file or directory' naming the literal star — but"
    echo "# it expands one happily at http level. That is the only reason this"
    echo "# file wraps its own directive."
    echo "#"
    echo "#   https://www.cloudflare.com/ips/"
    echo "geo \$remote_addr \$tk_edge {"
    echo "    default 0;"
    echo
    sed 's/$/ 1;/' "$RAW" | sed 's/^/    /'
    echo "}"
} > "$GEO_TMP"

install -m 644 "$ALLOW_TMP" "$ALLOW"
install -m 644 "$GEO_TMP" "$GEO"

echo "wrote $ALLOW and $GEO (${COUNT} ranges)"
if command -v nginx >/dev/null 2>&1; then
    nginx -t && echo "run:  systemctl reload nginx"
fi
